version: '3.8'

services:
  # optional notmuch mail container
  # if you already have notmuch configured or running
  # on your host you can omit this service
  voyage-mail:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${NOTMUCH_DB_PATH:-./mail}:/mail
      - ${CONFIG_PATH:-./config}:/config
    environment:
      - SYNC_FREQUENCY=${SYNC_FREQUENCY:-15m}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD:-}
      - NOTMUCH_CONFIG=/config/notmuch/config
    restart: unless-stopped
  # voyage api container tbd
